id: I511E1C41
source: https://sakyaresearch.org
source_file: null
initial_creation_type: input
imported: '2022-06-18T20:38:11.628588'
last_modified: '2022-06-18T20:38:11.628605'
parser: null
source_metadata:
  title: Fundamentals of Turning the Wheel of Dharma
  author: gser mdog paN chen shAkya mchog ldan/
  description: 'Digital version 4.0 {Wylie}; WYLIE COPY of master xml (completed:
    2012-09); linebreaks encoded, revision in process, no thematic TEI markup'
  file_info:
  - 'Language: Wylie'
  - 'Coverage: Full Text'
  - 'Accessible: publicly'
  responibilities:
  - Digital edition:Sakya Research Centre (src)
  - Text input:Volker Caumanns (vc)
  - Editorial process:Volker Caumanns (vc), Mathias Fermer (mf)
  - TEI Encoding:Sakya Research Centre
  - TEI Markup:-
  - Revisions/Corrections:Volker Caumanns (vc)
  text_witnesses: https://sakyaresearch.org/sources/132
  bases:
    615c:
      title: Fundamentals of Turning the Wheel of Dharma
      order: 1
      base_file: 615c.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
